### ISSUE TITLE
Clay requires X and GTK despite being a console application

### ISSUE THREAD

**Issue by ValentijnvdBeek** [and3rson/clay#11]
As discussed in issue #7 Clay relies on the Keybinder module to define global _X_ keybinds using a shim _GTK_ program. This means that you need to install both to be able to run Clay without getting any warning messages. Which is a bit silly seeing that Clay is a console program without any graphical elements and it would be entirely reasonable to run it headless (ex. on a raspberry pi connected to a speaker). 

The Keybinder should probably become an optional dependency depending on whether X is running or not.

**Comment by and3rson** [comment]
That's right, and it has been bothering me. I fact GTK is used *just* to use the global hotkeys.

I think I'm simply going to prevent "Global hotkeys will not work" notification and display it in "Debug" tab instead. Also, Clay does not strongly rely on Keybinder (i. e. it's not listen in requirements.)

**Comment by ValentijnvdBeek** [comment]
Pull request #12 should hopefully be along the lines of what you want.

**Comment by parkerlreed** [comment]
How would one use this over SSH? (Computer is hooked into speakers)

Using JuiceSSH on my phone, pressing Alt and then 9 just inputs 9. There's no way for me to get to the Settings page.
