### ISSUE TITLE
thumbs up playlist isn't listed

### ISSUE THREAD

**Issue by ecocode** [and3rson/clay#22]
On the playlist tab:
the automatically maintained 'Thumbs up' playlist isn't listed

**Comment by Fluctuz** [comment]
it looks like the 'rating' branch has the "Thump up" playlist implemented, but I am not sure if the branch works

**Comment by ValentijnvdBeek** [comment]
The branch works but the display of the thumbs up isn't accurately displayed yet.

**Comment by ValentijnvdBeek** [comment]
Should be fixed in #26
