### ISSUE TITLE
Font problem with Monospace Regular Powerline

### ISSUE THREAD

**Issue by metaheavens** [and3rson/clay#25]
I have a font problem that you can see below:

![2018-05-02-165614_953x21_scrot](https://user-images.githubusercontent.com/14920788/39530776-f29f2b18-4e29-11e8-9ed9-1c7e7db42716.png)

**Comment by carneeki** [comment]
I have the same font problem in commit 40390c4, I also have powerline installed. Toggling the value `clay_settings:`/`unicode` between `true` and `false` in `~/.config/clay/config.yaml` did not fix this.
