### ISSUE TITLE
Failed to request Media URL:

### ISSUE THREAD

**Issue by JPRuehmann** [and3rson/clay#3]
Hello

Every time I try to start a song I get the following Error.

Failed to request Media URL: Store Tracks require a Subscription to stream. (https://goo.gl/v1wvht)

How can I make it Play my Songs?
Thanks,

**Comment by and3rson** [comment]
Does it happen as well if you try to play a song on the search page?

**Comment by JPRuehmann** [comment]
Yes, as well.

**Comment by and3rson** [comment]
@JPRuehmann can you update to 0.5.6 (there's a new "Debug" tab there) and paste the error here?

**Comment by JPRuehmann** [comment]
GP::ListPlaylistEntries(*(), **{'max_results': 20000, 'updated_after': None, 'start_token': None})

**Comment by and3rson** [comment]
Can you also post an error that appears in debug tab when you try to play a song?

**Comment by JPRuehmann** [comment]
![screenshot_20180201_113936](https://user-images.githubusercontent.com/4321829/35674502-284c69aa-0745-11e8-8245-2abb78888366.png)

**Comment by and3rson** [comment]
@JPRuehmann can you hit Alt+M on some song and post values of "source" and "storeID" fields?

**Comment by JPRuehmann** [comment]
![screenshot_20180201_143743](https://user-images.githubusercontent.com/4321829/35681386-83b3a390-075d-11e8-8a22-850afc9e2499.png)

**Comment by JPRuehmann** [comment]
Yes, on my Mobile everything works fine.
By the Way I don´t have a Abo.
I am buying the Tracks one for one.
Thanks,

**Comment by and3rson** [comment]
Hey @JPRuehmann, sorry for the delay. Can you try version 0.6.1 and see if it works?

**Comment by and3rson** [comment]
@JPRuehmann I've just pushed 0.6.2, it should be working now. I've tested it with purchased tracks. Let me know if it works :)

**Comment by and3rson** [comment]
Related: stevenleeg/geemusic#42

**Comment by and3rson** [comment]
> raise NotSubscribed("Store tracks require a subscription to stream.")

I've had this issue as well. It happens when a user doesn't have a subscription, but is trying to play some uploaded or purchased tracks.

I fixed this by using the following logic in my code:

```python
if mobile_client.is_subscribed:
    track_id = track.storeId  # (or track_id.id)
else:
    track_id = track.id  # TODO: Handle missing "id"
mobile_client.get_stream_url(track_id)
```

The deal here is that most tracks have `id` (library ID) and `storeId` (store ID). To play purchased tracks, you need to pass the library ID (`id`) to `get_stream_url`, **NOT** the `storeId`.

**Comment by JPRuehmann** [comment]
Hello
Thanks for the Quick Help.
It now works like a charm.
Great App.

**Comment by eyalzek** [comment]
Has a fix for this been merged? I'm trying to find the relevant code in order to change it on v 0.7.2 but can't find it... This looks like the closest:
https://github.com/and3rson/clay/blob/0.7.2/clay/gp.py#L244-L248

**Comment by syslino** [comment]
I'm still getting the same error!
- Clay Player 1.1.0 (amber storm)

**Comment by syslino** [comment]
I'm still getting this error. Here's the message from the debug tab. https://pastebin.com/iVkRM6i9

- Clay Player 1.1.0 (amber storm)
- Archlinux, everything updated
- Python 3.7.2
- vlc 3.0.6-0-g5803e85f73
- Installed in fresh venv
- Paid All Accesss. Before I got AA, I bought some songs off the store, if that is relevant.

I'm paying  for Youtube premium which includes access to Play Music and YT Music in my region (Germanny).
