### ISSUE TITLE
Thumbs up playlist

### ISSUE THREAD

**Issue by nomarkeu** [and3rson/clay#30]
I can't find the autocreated thumbs up playlist.

**Comment by ValentijnvdBeek** [comment]
What version are you running?

**Comment by nomarkeu** [comment]
I don't know how to check the version. I installed from pip. Is there a command to check version?

**Comment by ValentijnvdBeek** [comment]
It is on the bottom left of the screen but if you installed through pip it doesn't have that feature.

**Comment by nomarkeu** [comment]
Version is 1.0.2. It's a crucial feature for me. I'll see if can install from source untill a new release.

This is off-topic but is there a way to install it from source and use the usual **clay** command/ instead of ./clay/app.py?

**Comment by ValentijnvdBeek** [comment]
Making a file called clay in ~/.local/bin/ with the following content should work:
``
#!/bin/sh

CLAY_PATH="/path/to/clay"
source "$CLAY_PATH/.env/bin/activate"
$CLAY_PATH/clay/app.py
``
You can check whether it is calling the right script using the `which` command

**Comment by nomarkeu** [comment]
It doesn't seem to get all the songs in the list. I can't seem to ascertain the general behaviour. If I add the song to the library by right-clicking (from the gplaymusic website) it shows up in clay. But some other songs  that I uploaded to gplaymusic (they don't have the add/remove from libary option) don't show up as well.
