### ISSUE TITLE
Rating Icon KeyError

### ISSUE THREAD

**Issue by jacsmith21** [and3rson/clay#31]
When converting tracks to a songlist, a KeyError occurs as 3 is not in `RATING_ICONS`. This is the line where the error occurs:
```python
self.rating = self.RATING_ICONS[track.rating]  # track.rating = 3

# reference
RATING_ICONS = {
    0: ' ',
    1: u'\U0001F593' if _unicode else '-',
    4: u'\U0001F593' if _unicode else '-',
    5: u'\U0001F592' if _unicode else '+'
}
```

Looking at my account, the song that causes this issue has no thumb so adding `3: ' ',` seems to fix the issue.

**Comment by and3rson** [comment]
Thanks for the report! I've added the missing values. It's weird how Google stores ratings.
