### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by schorsch3000** [and3rson/clay#6]
I know it's documented as properly non-working.
with an 2FA account clay will not work.
I'm going to try generating an app-specific-password later today to se if we can work around for now.

**Comment by and3rson** [comment]
Thanks! Let us know once you have any updates.

**Comment by schorsch3000** [comment]
i can't get clay up and running at my pc at home, since my libprotobuf is to old, but i'll give it a try tomorrow at the office (where is listen to music all day long).

**Comment by schorsch3000** [comment]
So, using a app-specific password works as intended.

I've got some question there, i'm not sure if i should open a ticket for.

I'm "only" able to listen to my uploaded music, nut the music-lib you'll get with the subscription.
is this intended, not done yet, a bug, or just a plain old pebkec?

**Comment by and3rson** [comment]
Hmm, interesting. Listening to any track using a subscription should actually work. Can you open a new ticket and provide more info there?

**Comment by schorsch3000** [comment]
Sure.
Im not sure about the "more info", but i'll make make it a wishlist.

Back to topic:
while app specific passwords work, security wise, that defeats the 2FA purpose.
is 2FA on the roadmap?

**Comment by and3rson** [comment]
Currently entire communication with GP servers is handled by gmusicapi library. I haven't checked if they have 2FA, but unfortunately I think that's something that is missing.

**Comment by schorsch3000** [comment]
At least it's not documented, so it'S out of this project's scope.
So should this issue be closed or kept as a reminder?

**Comment by and3rson** [comment]
I think it makes sense to close this - it's now totally up to the simon-weber/gmusicapi devs to implement this.
